### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by shikislav** [dvygolov/BinomoCloaker#1]
Привет, спасибо за твою клоаку бро, можешь мне помочь с настройками? Старая версия норм работает, а новая когда открываю сайт просто белый листок, я так понял просто бросаешь 2 ленда в папки и должно все быть ок, напиши мне плз в телеграм @gibbich , илм на почту davdwer@gmail.com. Спасибо

**Comment by dvygolov** [comment]
Пожалуйста) да, в целом ща бросаешь вайт и в папку white, а обычный в папку land и должно работать. Вообще, в новых версиях только фильтрация по user agent-у добавилась и работа с Google Tag Manager. Если тебе этого всего не нужно, то можно пользоваться старой и не париться.

**Comment by dvygolov** [comment]
> Привет, спасибо за твою клоаку бро, можешь мне помочь с настройками? Старая версия норм работает, а новая когда открываю сайт просто белый листок, я так понял просто бросаешь 2 ленда в папки и должно все быть ок, напиши мне плз в телеграм @Gibbich , илм на почту [davdwer@gmail.com](mailto:davdwer@gmail.com). Спасибо

Глянь я там в паблике обновил статью про кло с учётом изменений в новой версии.
