### ISSUE TITLE
Смарт линк

### ISSUE THREAD

**Issue by EvillProfit** [dvygolov/BinomoCloaker#10]
А можно его как то реализовать при работе со смартлинкой?

**Comment by dvygolov** [comment]
Можно вместо показа лендингов сделать переход по смартлинку, допилить надо
будет всего-ничего, думаю рублей за 200 любой фрилансер сделает.

**Comment by dvygolov** [comment]
> 
> 
> А можно его как то реализовать при работе со смартлинкой?

Добавил возможность редиректа для black-действия.
