### ISSUE TITLE
указание адреса вайта для фреймворка

### ISSUE THREAD

**Issue by max11** [dvygolov/BinomoCloaker#12]
Привет! Подскажи, можно ли как то указать внешнюю папку для вайта, если он на фреймворке, там зависимости видимо не срабатывают, показывает дефолтный ответ фреймворка что страница не существует.

**Comment by dvygolov** [comment]
Ты можешь перемещаться по папкам. Скажем, загрузить из папки white,
находящейся на уровень выше - это ../white

**Comment by max11** [comment]
Да, уже разобрался, но фреймворк, тот же ларавел, через curl не подгружается полностью. Наверно проще клоаку прямо в него встроить.

**Comment by dvygolov** [comment]
Не, такое я точно не тестил, я хз, зачем арбитражнику Laravel) Для таких
вариантов лучше Javascript-подключение использовать, но его я ещё не
запилил...
