### ISSUE TITLE
Web pages automatically adapt to mobile phone and computer issues

### ISSUE THREAD

**Issue by linkangren** [dvygolov/BinomoCloaker#15]
The white web page cannot automatically adapt to the screen, and the mobile phone displays the computer version of the web page.Yesterday, the Google vote on Facebook failed.

**Comment by dvygolov** [comment]
The cloaker doesn't change the ability of the white page to adapt to various screen resolutions and mobile devices. If the white page is not adaptive there's nothing you can do about it but to change its code :-)
