### ISSUE TITLE
The latest version, Logs page 403 error

### ISSUE THREAD

**Issue by gitodo** [dvygolov/BinomoCloaker#16]
Hi,

Open the Logs page, it shows 403 Forbidden / nginx

When I open the Logs page, such as https://my.domain/logs?password=11111, an error appears on the page.

But, in the logs folder, I can see the csv files

Thx.

**Comment by gitodo** [comment]
I found the answer

In the latest version, in the Logs folder, you deleted index.php and statistics.php

**Comment by gitodo** [comment]
ok, you moved the core file of logs to admin, so the correct way to open logs should be
https://my.domain/admin?password=12345

**Comment by dvygolov** [comment]
> 
> 
> ok, you moved the core file of logs to admin, so the correct way to open logs should be
> https://my.domain/admin?password=12345

Correct, I've made a GUI for settings but didn't find time to update the docs, sorry) It will be done in January I suppose...
