### ISSUE TITLE
Fatal error: Trait 'SleekDB\Traits\IoHelperTrait

### ISSUE THREAD

**Issue by semenov-dev** [dvygolov/BinomoCloaker#18]
Привет, подскажи, что не так? 
поставил кло по инструкции, выдаёт такую ошибку если перехожу на домен самого сайта, что я сделал не так
Fatal error: Trait 'SleekDB\Traits\IoHelperTrait' not found in /var/www/u000000/data/www/sam-sait.com/db/Store.php on line 32

видел правки этих файлов как раз 4 дня назад, а я скачал 3 дня назад. Может наткнулся на баг?

**Comment by dvygolov** [comment]
Да, это баг, отпишу, как поправлю сегодня.

**Comment by Value6666** [comment]
Fatal error: Uncaught Error: Class 'SleekDB\Classes\IoHelper' not found in /var/www/u1298653/data/www/oza.sp/db/Store.php:75 Stack trace: #0 /var/www/u1298653/data/www/oza.sp/admin/db.php(16): SleekDB\Store->__construct('blackclicks', '/var/www/u36873...') #1 /var/www/u1298653/data/www/oza.sp/admin/index.php(32): get_black_clicks(1614027600, 1614113999) #2 {main} thrown in /var/www/u1298653/data/www/oza.sp/db/Store.php on line 75  ошибочка вышла

**Comment by dvygolov** [comment]
Починил

**Comment by semenov-dev** [comment]
у меня не заработало, Ошибка такая же как у Value6666

Fatal error: Uncaught Error: Class 'SleekDB\Classes\IoHelper' not found in 
.....
/db/Store.php on line 75
