### ISSUE TITLE
Fatal error: Uncaught Error: Class 'SleekDB\Classes\IoHelper' not found in

### ISSUE THREAD

**Issue by semenov-dev** [dvygolov/BinomoCloaker#19]
Ошибка такая же как у Value6666  https://github.com/dvygolov/BinomoCloaker/issues/18#issuecomment-784431274

Fatal error: Uncaught Error: Class 'SleekDB\Classes\IoHelper' not found in
.....
/db/Store.php on line 75

**Comment by dvygolov** [comment]
Уже исправлено, скачай последнюю версию.
