### ISSUE TITLE
Fatal error: Uncaught GeoIp2\Exception\AddressNotFoundException: 

### ISSUE THREAD

**Issue by kenan3507** [dvygolov/BinomoCloaker#21]
I installed it last night and it worked flawlessly. I get this error when I wake up in the morning. I tried 5-6 different ip. Vpn and local mobile ip. I always get the same error. What could be the problem?

Fatal error: Uncaught GeoIp2\Exception\AddressNotFoundException: The address 178.250.168.225 is not in the database. in phar:///home/robksgnb/sms.mydomain.com/bases/geoip2.phar/src/Database/Reader.php:248 Stack trace: #0 phar:///home/robksgnb/sms.mydomain.com/bases/geoip2.phar/src/Database/Reader.php(229): GeoIp2\Database\Reader->getRecord('Asn', 'GeoLite2-ASN', '178.250.168.225') #1 phar:///home/robksgnb/sms.mydomain.com/bases/geoip2.phar/src/Database/Reader.php(129): GeoIp2\Database\Reader->flatModelFor('Asn', 'GeoLite2-ASN', '178.250.168.225') #2 /home/robksgnb/sms.mydomain.com/bases/ipcountry.php(66): GeoIp2\Database\Reader->asn('178.250.168.225') #3 /home/robksgnb/sms.mydomain.com/core.php(63): getisp('178.250.168.225') #4 /home/robksgnb/sms.mydomain.com/core.php(42): Cloaker->detect() #5 /home/robksgnb/sms.mydomain.com/index.php(14): Cloaker->__construct(Array, Array, Array, '', false, Array, Array, Array, Array, true, Array, false) #6 {main} thrown in phar:///home/robksgnb/sms.mydomain.com/bases/geoip2.phar/src/Database/Reader.php on line 248

**Comment by kenan3507** [comment]
İts working with my home internet isp but doesnt work with Turkcell mobile isp for now.

**Comment by dvygolov** [comment]
just update the MaxMind Country database and you are good to go
С уважением,
Выголов Даниил.

**Comment by kenan3507** [comment]
Can you give some details? Where and how do I do this?

**Comment by kenan3507** [comment]
Thank you but can you give some details? Where and how do I do this?

**Comment by dvygolov** [comment]
Just google MaxMind and you'll find their website. Register there and
download free country database there. Then put it into bases folder, it
should replace the old one there.

**Comment by kenan3507** [comment]
Thank you for your help. I downloaded GeoLite2-Country.mmdb and changed with old. But still the same. Very interesting but its doesnt work with TURKCELL isp's. And also its work within Nordvpn many countries but wwhen i enter with Turkey Nord Ip's its give error.

**Comment by kenan3507** [comment]
I also changed GeoLite2-ASN.mmdb and its solved.  Thank you so much for providing such script for free and helping.

на здоровья!
