### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by kenan3507** [dvygolov/BinomoCloaker#22]
I am using WHM/Cpanel over my Azure server. My Php Version is 7.4 and I am using Cloudflare SSL.

Screenshot of the error I got:  https://prnt.sc/25hilsq

I am getting this error on all pages.

Homepage or mydomain.com/ admin?password=12345

So where could the problem be?

Thank you.

Error Log : htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration

**Comment by d1monch1k** [comment]
open .htaccess

delete this

php_flag  display_errors 1
php_flag  display_startup_errors 1
php_value  error_reporting 2047

done
