### ISSUE TITLE
ошибки при загрузке

### ISSUE THREAD

**Issue by newdayo** [dvygolov/BinomoCloaker#25]
Здравствуйте) установил вашу кло на хостинг beget и при загрузки блеков и вайтов через кло выдает сначала кучу ошибок а потом страничка грузится, вот текст ошибок

Deprecated: Return type of GeoIp2\Model\AbstractModel::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/b/begemoeg/mysite.com/public_html/bases/geoip2.phar/src/Model/AbstractModel.php on line 63 Deprecated: Return type of GeoIp2\Record\AbstractRecord::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/b/begemoeg/mysite.com/public_html/bases/geoip2.phar/src/Record/AbstractRecord.php on line 57 Warning: Cannot modify header information - headers already sent by (output started at phar:///home/b/begemoeg/mysite.com/public_html/bases/geoip2.phar/src/Model/AbstractModel.php:8) in /home/b/begemoeg/mysite.com/public_html/cookies.php on line 4 Warning: session_start(): Session cannot be started after headers have already been sent in /home/b/begemoeg/mysite.com/public_html/cookies.php on line 9

сайт проброшен через клауд, но only DNS, сертификат на бегете выпущен бесплатный
К сожалению в коде не силен, можете помоч разобраться?

**Comment by dvygolov** [comment]
Поставьте версию PHP 7.4
С уважением,
Выголов Даниил.

**Comment by newdayo** [comment]
спасибо) буду дальше разбираться)
