### ISSUE TITLE
На black в гугл аналитике высвечивается посещения с фб

### ISSUE THREAD

**Issue by omnikross** [dvygolov/BinomoCloaker#4]
Ещё раз привет, такой вопрос, сам не смог понять почему так, смотри, привязал я гугл аналитику на основную связку. Модеры все идут на вайт, это проверял  в веб визоре весь день) Но вот проблема в чем, в аналитике, на ленде, в посетителях в реальном времени можно заметить что появляютя вот такие записи "/?fbclid=" и дальше длинное значение. Может ты знаешь что это за проверки такие от фб?

**Comment by dvygolov** [comment]
Эмм, а почему ты думаешь, что это проверки? По-моему это обычные переходы на ленд посетителей. ФБ же дописывает к ссылке такие хвосты.
