### ISSUE TITLE
htmlprocessing.php не обрабатывает ссылки в стилях внутри url()

### ISSUE THREAD

**Issue by nikodenn** [dvygolov/BinomoCloaker#5]
Привет!

Например вот такие ссылки не обрабатываются: 

style="background-image:url('wp-content/uploads/2017/06/siia-logo_b-n.png');"

Я вставил в htmlprocessing.php вот такой код, как внизу. Для меня работает.

$html = preg_replace('/url\(\'*(?!http)([^\'\"]+)\'*/', "url($baseurl\\1", $html);

**Comment by nikodenn** [comment]
так что, я тогда закомичу...?

**Comment by dvygolov** [comment]
Без проблем, конечно.
С уважением,
Выголов Даниил.
