### ISSUE TITLE
htmlprocessing.php не обрабатывает ссылки в параметрах srcset

### ISSUE THREAD

**Issue by nikodenn** [dvygolov/BinomoCloaker#6]
Например вот в таких: 

srcset="/wp-content/uploads/2019/03/LocandinaSIIA2019-213x300.jpg 300w, /wp-content/uploads/2019/03/LocandinaSIIA2019-400x284.jpg 400w, /wp-content/uploads/2019/03/LocandinaSIIA2019.jpg 768w, /wp-content/uploads/2019/03/LocandinaSIIA2019.jpg 1024w"

**Comment by dvygolov** [comment]
это да, даже не сталкивался с такими лендами и про этот html атрибут не слышал)

**Comment by nikodenn** [comment]
Да я сам его на вордпрессовском сайте увидел.
На лендах он обычно и не используется, (пока :) думаю) но на вайтпейдже мне попался.

**Comment by dvygolov** [comment]
Закрываю, потому что править не буду, слишком редкий случай.
