### ISSUE TITLE
Где взять свежий список ботов?

### ISSUE THREAD

**Issue by nikodenn** [dvygolov/BinomoCloaker#7]
Привет!

Скажи пожалуйста, где взять свежий список ботов?
Тот, что закомичен уже 5-тимесячной давности.

P.S.: большое спасибо тебе за клоаку Буду её тестить.

**Comment by dvygolov** [comment]
Привет, взять его можно на каналах телеги по сливам. Там проскакивают базы из Кейтаро. Также если есть доступ на платные форумы типа STM, там тоже есть. Есть тема по ботам на fb-killa.

**Comment by nikodenn** [comment]
На fb-killa тему про ботов не нашёл. Зато нашёл твоё интервью :) Первый комент к нему - от меня :)

А тема про ботов случайно не в приватном разделе? Можешь кинуть ссылку?

P.S.: Нашёл твой паблик - почитаю :)

**Comment by nikodenn** [comment]
Насчёт файла базы ботов. Один добрый чел в чате Everad поделился свежей базой Кейтаро.

Я значит правильно угадал, что используется текстовый bots.dat из Кейтаро в чистом виде, только удаляется комент в первой строчке :)

Я посмотрел в коде, он заглатывается целиком как есть без отсева повторов и тут же проверяется на пересечение с IP клиента как строковый литерал %)
Как я был наивен :)

		$bot_ips=file_get_contents("bots.dat");
		$ip_black_checker=  stristr($bot_ips, $current_ip);
		
		if (!empty($ip_black_checker))
		{
			$is_bot=1;
		}

**Comment by nikodenn** [comment]
А GeoIP.dat - это случайно не GeoLiteCity.dat ?

**Comment by dvygolov** [comment]
> А GeoIP.dat - это случайно не GeoLiteCity.dat ?

Почти, только это предыдущая версия MaxMind GeoIP, если добавишь последнюю, запили pull request плиз!

**Comment by dvygolov** [comment]
> Насчёт файла базы ботов. Один добрый чел в чате Everad поделился свежей базой Кейтаро.
> 
> Я значит правильно угадал, что используется текстовый bots.dat из Кейтаро в чистом виде, только удаляется комент в первой строчке :)
> 
> Я посмотрел в коде, он заглатывается целиком как есть без отсева повторов и тут же проверяется на пересечение с IP клиента как строковый литерал %)
> Как я был наивен :)
> 
> ```
> 	$bot_ips=file_get_contents("bots.dat");
> 	$ip_black_checker=  stristr($bot_ips, $current_ip);
> 	
> 	if (!empty($ip_black_checker))
> 	{
> 		$is_bot=1;
> 	}
> ```

Верно, но туда впилена ещё часть с fb-killa. Тему на форуме не помню, весной её искал. Она в паблике, не в приватном разделе.

**Comment by nikodenn** [comment]
> Верно, но туда впилена ещё часть с fb-killa. Тему на форуме не помню, весной её искал. Она в паблике, не в приватном разделе.

Ок. Поищу ещё

**Comment by nikodenn** [comment]
Привет!

Вот эта тема на fb-killa https://fb-killa.pro/index.php?threads/spisok-ip-i-signatur-botov-i-moderov-dlja-keitaro.1962/page-6?
Там последнее обновление списка поступило 27 января.
Тогда, я так понимаю, что твой bots.dat содержит эти обновления...?
А как ты поступал с подсетками тога? разворачивал в полный список?

**Comment by dvygolov** [comment]
Да тема эта. Блин, а я чё-т уже и не помню, как я сделал) Вроде я сначала вместе с масками добавлял и писал код, чтобы по ним считалось всё. Но куда это всё делось??))) Короче, видимо это надо провернуть ещё раз.

**Comment by nikodenn** [comment]
Я уже дописал поддержку CIDR масок. Тестирую. Еще сделаю фильтр по по IP V6, и есть идея как сделать вайтпейдж не локальной копией, а полнім проксированием всех ссылок на внешний сайт. Пока у ФБ крышу сносит - займусь этим. А когда его попусти - потестирую и тогда уже буду создавать пуш реквесты.

**Comment by dvygolov** [comment]
> Я уже дописал поддержку CIDR масок. Тестирую. Еще сделаю фильтр по IP V6.
> И есть идея как сделать вайтпейдж не локальной копией, а полным проксированием всех ссылок на внешний сайт.
> А еще готовлю большой апдейт базы IP и скрипт для её мержа из разніх кусков и оптимизации.
> 
> Пока у ФБ крышу сносит - занимаюсь этим. А когда его попустит - потестирую и тогда уже буду создавать пулл реквесты.

Апплодирую стоя, бро! Жду реквест))

**Comment by dvygolov** [comment]
Вот канал в Телеге, где свежие базы выкладывают https://t.me/arbitragetrafik

**Comment by dvygolov** [comment]
> Я уже дописал поддержку CIDR масок. Тестирую. Еще сделаю фильтр по IP V6.
> И есть идея как сделать вайтпейдж не локальной копией, а полным проксированием всех ссылок на внешний сайт.
> А еще готовлю большой апдейт базы IP и скрипт для её мержа из разніх кусков и оптимизации.
> 
> Пока у ФБ крышу сносит - занимаюсь этим. А когда его попустит - потестирую и тогда уже буду создавать пулл реквесты.

Ну как, не допилил ещё?

**Comment by nikodenn** [comment]
> 
> 
> Вот канал в Телеге, где свежие базы выкладывают https://t.me/arbitragetrafik

Спасибо! Тольео открыл и сразу попал на интересный материал :)

**Comment by nikodenn** [comment]
> 
> 
> > Я уже дописал поддержку CIDR масок. Тестирую. Еще сделаю фильтр по IP V6.
> > И есть идея как сделать вайтпейдж не локальной копией, а полным проксированием всех ссылок на внешний сайт.
> > А еще готовлю большой апдейт базы IP и скрипт для её мержа из разніх кусков и оптимизации.
> > Пока у ФБ крышу сносит - занимаюсь этим. А когда его попустит - потестирую и тогда уже буду создавать пулл реквесты.
> 
> Ну как, не допилил ещё?

Привет! Нет :(
Сейчас экстренно ищу где заработать средства на бюджет.

Апдейт базы ботов будет, но чуть позже. Отфильтровывание всего трафа IPV6 тоже сделаю, хотя это уже вот-вот станет вредной фичей, надо нормальную поддержку IPV6 пилить.
А вот с проксированием решил пока не заморачиваться, т.к. сейчас локальный вайтпейдж работает эффективнее.

**Comment by dvygolov** [comment]
Бро, привет! Подвижек новых нет пока?

**Comment by nikodenn** [comment]
Привет, Бро! В поисках бюджета попал в арбитражную команду - затянуло. Даю угля стране :) Тут развратили Кейтаро. Чертовски удобная штука. Так что я временно приостановил работу над клоакером. Сделаю пулреквест того что есть как только найду пару часов свободного времени.

**Comment by dvygolov** [comment]
О, ну поздравляю, это хорошие новости!
Да, закинь, плз, что запилил, как будет время, пусть начинающие
развлекаются)

**Comment by Evoads** [comment]
Ребят, 
базы ботов состоянием 17/04/20 - https://cloud.mail.ru/public/2dGw/5foYER1bo
(Большое спасибо человеку с fb-killa - https://fb-killa.pro/index.php?threads/spisok-ip-i-signatur-botov-i-moderov-dlja-keitaro.1962/page-9)

Но вопрос, как добавить базы моб. операторов и городов?
Кто-то подскажет как все в кучи собрать?
И нужно ли вообще добавлять базы моб. операторов и гео ip по городам?

**Comment by dvygolov** [comment]
Фильтров по моб.операторам и городам в этой клоаке нету, если есть необходимость - нужно допиливать. Есть только страны. База GeoIP используется стандартная MaxMind, но устаревшей версии, можно переключить без особых проблем на последнюю. Только там, кажется, она тоже платной стала...

**Comment by dvygolov** [comment]
Обновил базы до последних, как по определению ГЕО так и по ботам.

**Comment by alpiyev99** [comment]
Благодарю, есть обнова на 2023?
