### ISSUE TITLE
клоака пробилась сходу при модерации с $full_cloak_on=1

### ISSUE THREAD

**Issue by nikodenn** [dvygolov/BinomoCloaker#9]
Привет!

Что-то клоака пробилась сходу при модерации с $full_cloak_on = 1.
У кого какой сейчас опыт использования этой клоаки?

![отчёт maskFB](https://user-images.githubusercontent.com/48717318/65842897-5b8a2f80-e337-11e9-8dfd-a54cbfe228cb.png)

**Comment by dvygolov** [comment]
Это навряд ли, скорее всего просто улетело за клоакинг, что в последнее время не редкость.
Клоака не может пробиваться при full_cloak. Физически) Потому что там по факту клоакинга нету, просто показывается вайт) Если бы ты поставил Яндекс.метрику на блек то не увидел бы на нем кликов.

**Comment by nikodenn** [comment]
Я сначала подумал, что это из-за того как организована вайтпейдж. Есть признаки отго, что это копия сайта. Она скачана httrack, по структкре это видно. При открытии любой внутренней ссылки появляется новая папка, но струтура сайта при этом не меняется. Я бы на месте индусов задумался.
Но старшие товарищи просветили, что это очередной ПМС фейсбука. Так что я закрываю тикет
